# Generated by Django 3.2.23 on 2023-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_vote_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="rate",
            field=models.FloatField(default=0),
        ),
    ]
