# Generated by Django 3.2.23 on 2024-01-23 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blog_rate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
    ]
