# Generated by Django 3.2.23 on 2024-04-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_alter_vote_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="count_of_voters",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(default="Blog post content"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(default="Blog post title", max_length=30),
        ),
    ]
